name: $pluginName
version: $pluginVersion
main: $pluginMain
api-version: 1.17
authors: [ TeamVeryMC, kill00 ]
depend:
  - ProtocolLib
website: https://github.com/TeamVeryMC/A-Month-Server_Season1

commands:
  ams:
    description: 한 달 서버 관리 명령어
    permission: op
  up:
    description: 가장 높은곳으로 이동